### ISSUE TITLE
Request Documentation

### ISSUE THREAD

**Issue by technolingo** [jantoniomartin/condottieri_notification#1]
Hi, 

Thank you for creating this app. I found it leaner than some other apps, just what I need (to show notices on signing in). 

Could you explain a bit more how to get started with this app? I already have pinax-notifications 4 installed, do I need to uninstall that or just remove it from INSTALLED_APPS? What about its variables in settings.py? Do I have to remove pinax-notifications' urls? And how to access the notices in context? 

Sorry for so many questions. Many thanks in anticipation!

**Comment by jantoniomartin** [comment]
I'm glad that you find it useful. You need to install pinax-notifications, then add 'pinax.notifications' and 'condottieri_notification' to INSTALLED_APPS. Then you need to add 'pinax.notifications.urls' and 'condottieri_notification.urls' to your urls.

Then, add the following item to `settings.PINAX_NOTIFICATIONS_BACKENDS`:

`('on site', 'condottieri_notification.backends.SiteBackend')`

**Comment by technolingo** [comment]
Thank you! Just figured it out. A very useful app.
